-- Migration: create chat_messages table
-- Description: Almacena el historial de conversaciones con IA por nota o global.

create table if not exists chat_messages (
  id bigint generated by default as identity primary key,
  note_id bigint references notes(id) on delete cascade,
  role text not null check (role in ('user', 'assistant', 'system')),
  content text not null,
  provider text not null,
  model text,
  retention_seconds bigint not null default 2592000,
  created_at timestamptz not null default now()
);

-- Permitir al usuario autenticado leer y escribir sus propios mensajes.
alter table chat_messages enable row level security;

create policy "Users can insert their own chat messages"
  on chat_messages for insert
  with check (auth.uid() is not null);

create policy "Users can read their own chat messages"
  on chat_messages for select
  using (auth.uid() is not null);

create policy "Users can delete their own chat messages"
  on chat_messages for delete
  using (auth.uid() is not null);

create index idx_chat_messages_note_id on chat_messages(note_id);
create index idx_chat_messages_created_at on chat_messages(created_at);
